### ISSUE TITLE
CTF Messages not appearing

### ISSUE THREAD

**Issue by Spac69** [CriticalFlaw/rayshud-Installer#10]
In CTF you would get a "popup" informing you and your team that:
- Your team picked the intelligence up.
- Your team has dropped the intelligence.
- Your team captured the intelligence.
- The enemy's intelligence returned to their base.
- The enemy has your team's intelligence.
- The enemy dropped your intelligence.
- Your intelligence has returned to your base.
- The enemy has captured your intelligence.

Although recently, that "popup" has stopped appearing. But yet I remember it being there. I have tried to reinstall rayshud, but yet that doesn't work.

**Comment by CriticalFlaw** [comment]
I haven't been able to reproduce the CTF notification not appearing. Restarting the game or reinstalling rayshud would likely fix the issue.

Also please report issues on the rayshud issue tracker: https://github.com/raysfire/rayshud/issues this tracker is strictly for the installer.
