### ISSUE TITLE
Crosshair Errors

### ISSUE THREAD

**Issue by swampuru** [CriticalFlaw/rayshud-Installer#14]
I have been using the WingsPlus crosshair for as long as the option was enabled, but the new update for the installer always puts the crosshair onto the far left, instead of the center. assistance please :s !
![20190418144702_1](https://user-images.githubusercontent.com/49767723/56393393-1e970a00-61e9-11e9-8824-3b3c69e3777f.jpg)

**Comment by CriticalFlaw** [comment]
Hello! Could you let me know the operating system, resolution and installer settings you're using? I'm on Windows 10, 1920x1080 with the installer settings screenshot below. I don't see the same issue in-game so I'll need your help replicating it so it can be fixed.

Also I presume you're using the latest versions of installer and rayshud (2.2 and 2019.0406 respectively)

![image](https://user-images.githubusercontent.com/6818236/56398065-c0801c00-6214-11e9-887e-644256905ff7.png)

![image](https://user-images.githubusercontent.com/6818236/56398076-c675fd00-6214-11e9-8448-9087c2499b5e.png)

**Comment by swampuru** [comment]
So I went into the hudlayout.res file with Notepad++ and when I enable the crosshair in there, it seems to work fine. I adjusted the values myself and everything seems to work fine, but with i try to do it with the installer, it sets it to the left, as shown in my picture. I'm on a Windows 10 and play with resolution 1280 x 1024. for now the crosshair hud is fine, but using the installer for it doesn't work

**Comment by swampuru** [comment]
also my chat keeps moving back to the lower right instead of staying at the top left

**Comment by CriticalFlaw** [comment]
Do you have the latest rayshud installed?

**Comment by swampuru** [comment]
yup, latest update and everything :s if you need any assistance on my part feel free to ask!

**Comment by CriticalFlaw** [comment]
Try backing up your current rayshud installation. Then do a fresh install with the installer. I suspect there might be some kind of file conflict. The installer updates HUD files using specified line numbers so if a line does not match then the write breaks.

**Comment by CriticalFlaw** [comment]
Future release will include the ability to set your own X/Y values for the crosshair position.

**Comment by swampuru** [comment]
So, I managed to fix this awhile ago. I looked inside the crosshair.res with Notepad++ and saw that there was now "Wide" position, just tall. So i added the wide and it was back to center ^^ guess the prior update removed that line for some reason

**Comment by CriticalFlaw** [comment]
That's good. It must have been a small error in the file writer that snuck in. I'll look into making it more "_bulletproof_" so these kind of problems don't happen. Closing this ticket.
