### ISSUE TITLE
rayshud_installer.exe doesn't open

### ISSUE THREAD

**Issue by konocubed** [CriticalFlaw/rayshud-Installer#20]
Version 3.0

Windows 10 Pro

I downloaded the .zip and unzipped all of its contents into a folder. Double-clicking rayshud_installer.exe doesn't open it. Double-clicking it in the .zip shows the Windows Defender SmartScreen prompt, but clicking 'Run Anyways' still shows nothing.

**Comment by CriticalFlaw** [comment]
Ive apparently uploaded the wrong version as a release. Fixed that now, could you try it again please?

**Comment by konocubed** [comment]
No change, same issue.

**Comment by CriticalFlaw** [comment]
Odd. Does it produce a log file in the root directory?

**Comment by konocubed** [comment]
Nothing, no log files.

**Comment by CriticalFlaw** [comment]
Do you have the NET Core 3.0 runtime installed?

**Comment by zornor** [comment]
Hello there. I am having the same issue. No change after installing .NET Core v3.0.0-preview7 and restarting, or running as admin. Using Windows 10 Home.

**Comment by CriticalFlaw** [comment]
Thank you for the reply. That's very odd, but I think it might be an issue with NET Core and it not yet being widely available. I'll roll back to NET Framework and we can give that a try, see if the issue lies in that. Apologies for the inconvenience, it was a poor design on my part to move the app to a developmental version of the framework.

**Comment by CriticalFlaw** [comment]
https://github.com/CriticalFlaw/rayshud-Installer/releases/tag/3.0

I've added a separate version running NET Framework `rayshud Installer-framework.rar` to the 3.0 release. Let me know if the same issue persists.

**Comment by zornor** [comment]
The .NET Framework 4.8 version works for me. Cheers!

**Comment by CriticalFlaw** [comment]
Excellent. If it works for @konocubed as well, then I'll pull out the NET Core migration and keep it at Framework 4.8 for the time being since it's more stable and has a higher install base.

**Comment by konocubed** [comment]
Same here, works just fine.

**Comment by CriticalFlaw** [comment]
Cheers guys, thank you for reporting and helping troubleshoot this.
