### ISSUE TITLE
Unable to Install my Set Up using Installer

### ISSUE THREAD

**Issue by FestivePybro** [CriticalFlaw/rayshud-Installer#21]
![image](https://user-images.githubusercontent.com/54483688/63642026-050d3f80-c66d-11e9-9b9c-4444fff1a458.png)

I get this message after clicking Install.

**Comment by CriticalFlaw** [comment]
Try extracting the installer to a non-temp location (for example My Documents) and try installing rayshud then. I because the installer is being run from AppData/Local/Temp it's messing things up

**Comment by FestivePybro** [comment]
Thank you!
