### ISSUE TITLE
Menu goes down after installing hud

### ISSUE THREAD

**Issue by Darudeee** [CriticalFlaw/rayshud-Installer#29]
![image](https://user-images.githubusercontent.com/57864209/69007774-e6a4a080-094a-11ea-9048-b87186f8a955.png)

**Comment by CriticalFlaw** [comment]
Does this happen with the clean installation of rayshud through the latest installer (version 3.3)?

**Comment by Darudeee** [comment]
Just installed on a clean tf2, same problem, so yeah

**Comment by Darudeee** [comment]
Oh, so this happens if i uncheck this setting
![image](https://user-images.githubusercontent.com/57864209/69063849-df05fa00-0a25-11ea-89ee-fb80d0438950.png)

**Comment by CriticalFlaw** [comment]
Thanks. I'll look into it after work and release a patch by tomorrow.

**Comment by Darudeee** [comment]
Nice! Thanks

**Comment by CriticalFlaw** [comment]
The issue has been fixed in the latest version (3.3.1). Thank you for reporting the issue.

https://github.com/CriticalFlaw/rayshud-Installer/releases/tag/3.3.1

**Comment by RunawaySheld123** [comment]
Just Like My Issue

**Comment by CriticalFlaw** [comment]
@RunawaySheld123 I've updated your original bug report with a note tying it to this issue.

**Comment by iBusterino** [comment]
after updating rays with the installer, the rays custom background is gone, how can i fix that?
