### ISSUE TITLE
Issue with selecting class menu

### ISSUE THREAD

**Issue by Ashetf2** [CriticalFlaw/rayshud-Installer#32]
When you put the mouse cursor between any class button (i.e. between Heavy and Enginner), the sound spams a lot.

**Comment by CriticalFlaw** [comment]
Does this only happen with the default class selection page and only between certain class options?

**Comment by CriticalFlaw** [comment]
Also in the future, please open non-installer issues to the rayshud issue tracker: https://github.com/raysfire/rayshud/issues

**Comment by Ashetf2** [comment]
Heres a video of the bug: 
https://youtu.be/VrygWxXS2og

**Comment by CriticalFlaw** [comment]
Thanks. The audio bug has been fixed here: https://github.com/raysfire/rayshud/commit/3025bdfea69b9fdf28ebc0c93066d1e62fbd48d7

It's included in the latest version v2020.0415
