### ISSUE TITLE
Pulse damage broke

### ISSUE THREAD

**Issue by omperus** [CriticalFlaw/rayshud-Installer#33]
After reinstalling the HUD with the latest update, pulse damage stopped working (at least with ThinCircle crosshair)
I added

> 	Animate ThinCircle						FgColor	"CrosshairDamage" 			Linear 0.0	0.0
> 	Animate ThinCircle	 					FgColor	"Crosshair" 				Linear 0.15	0.0

On hudanimations_custom "// Hitmarker Pulse" section and it started working again.

**Comment by CriticalFlaw** [comment]
Previously all crosshairs were being controlled by a single node **RaysCrosshair** but that became a pain to manage in the code, so the individual crosshair nodes (BasicCross, OpenCrossDot etc.) are now being used but they were all missing their entries in the hudanimations_custom.

Thank you for reporting this, I've added the missing animations in this commit: https://github.com/raysfire/rayshud/commit/eae8db1d9e08ad2aeb811f3eaaf74747aeeec917
