### ISSUE TITLE
Pulse Hitmarker Breaks The Moment Damage Is Delt

### ISSUE THREAD

**Issue by DJSylveon** [CriticalFlaw/rayshud-Installer#34]
The Pulse Hitmarker will breakcreating a second larger crosshair off to the right of the actual crosshair. This happens the moment damage is delt and stays there until the hud is reinstalled. The only changes made to the crosshair was making it OpenCrossDot and the color #FF10FF00.

**Comment by CriticalFlaw** [comment]
The second crosshair you see off to the side is the OpenCrossDot you've enabled, you can adjust its resting position by modifying the X and Y values in the installer. If you want to use just the custom crosshair you'll need to disable the TF2 crosshair in the Options.

If this doesn't sound like the issue you're having, make sure you're using the latest installer version.
