### ISSUE TITLE
How do i use the installer?

### ISSUE THREAD

**Issue by Johnny2007** [CriticalFlaw/rayshud-Installer#37]
So when using the installer, i make mu custom settings and etc. after that when i click on 'install' it freeses the app. and then, when i refresh the app, it says that it was installed. but when i check my custom directory, there's nothing there

**Comment by CriticalFlaw** [comment]
After you change your settings, you have to click on **Apply Changes** for them to be saved and applied. 

If after installing rayshud it's still not showing up in your `tf/custom` directory then the Steam directory you have set in your registry is different from where you have Team Fortress 2 installed. If that's the case, you'll have to click on **Change Directory** and specify where your `tf/custom` folder is. That should resolve the issue.
