### ISSUE TITLE
Pulse damage doesnt work? Transparency slider for colors.

### ISSUE THREAD

**Issue by omperus** [CriticalFlaw/rayshud-Installer#4]
First of all thanks for making this awesome installer.

Sadly the pulse damage doesn't work for me, is this a known issue?

![image](https://user-images.githubusercontent.com/4312673/42137414-02aac4ee-7d42-11e8-8561-a39fb6bc6a8d.png)

![image](https://user-images.githubusercontent.com/4312673/42137489-8325a890-7d43-11e8-9464-7713e53b9ffd.png)

Old installer used to have transparency for the colors and a configuration for damage numbers too, that would be a nice addition.

**Comment by CriticalFlaw** [comment]
I haven't found a way yet to implement transparency but I did fix the issue with the damage pulse not working https://github.com/CriticalFlaw/rayshud-Installer/commit/d2707ee2c88f174968c576ec15f49e8973edcd7c
