### ISSUE TITLE
Vanilla crosshair still showing up with the custom one

### ISSUE THREAD

**Issue by CammiePone** [CriticalFlaw/rayshud-Installer#40]
So I set a custom crosshair, and now I've got my old vanilla one rendering with the new one. Even setting the vanilla one to None doesn't hide it, and instead just renders the default one.
![image](https://user-images.githubusercontent.com/16853086/89550667-e9486e00-d7d7-11ea-90ca-5b2618dd44f6.png)

**Comment by CriticalFlaw** [comment]
If the game does not hide its own crosshair then that's an issue with the engine, not the hud or the installer.

**Comment by CammiePone** [comment]
Yeah, have been informed you have to run "crosshair size 0" in console. Wasn't sure if it was something that could be automated by the installer or not, hence why I didn't close the issue until now. Ah well
