### ISSUE TITLE
Error with the main menu?

### ISSUE THREAD

**Issue by Iv1ano** [CriticalFlaw/rayshud-Installer#41]
Hello! Just downloaded the hud and the installer, and the main menu looks like this no matter the setting (modern, classic or default). Any idea why?
![image](https://user-images.githubusercontent.com/69418300/89729334-38580280-da67-11ea-957a-77c003c3c218.png)

EDIT: Found the error, which you might want to look into - minimal scoreboard breaks the main menu background when checked. When unchecked, the main menu background works fine. However, the loading screen breaks in a similar fashion.

![image](https://user-images.githubusercontent.com/69418300/89729700-d8fbf180-da6a-11ea-94bb-27a4ad9e522f.png)

**Comment by CriticalFlaw** [comment]
Could you send a screenshot of the rayhud installer settings as you have them when this bug happens? In my testing, I haven't yet been able to reproduce this so it may be some odd combination of settings that's causing this.

**Comment by CriticalFlaw** [comment]
Actually scratch that, I think I know what the issue is. ~12 hours ago alongside the latest version of the installer was a small rayshud update that changed how main menu backgrounds are switched. I'm willing to bet you still have the pre-fix version of rayshud and that's why the backgrounds are missing. Please try removing the copy of rayshud you have in tf/custom and install a fresh copy, see if that fixes it.

**Comment by Iv1ano** [comment]
A fresh install did not work, unfortunately. 
![image](https://user-images.githubusercontent.com/69418300/89797019-f4472980-db5c-11ea-940d-a2557a23c780.png)
 Heres the installer currently.

**Comment by CriticalFlaw** [comment]
Could you post a screenshot of your `rayshud/materials/console` folder please?

**Comment by Iv1ano** [comment]
![image](https://user-images.githubusercontent.com/69418300/90027431-2090b080-dceb-11ea-9e1c-acc15a894979.png)

**Comment by CriticalFlaw** [comment]
You have an old version of rayshud. That folder should oly have the following three items:
![image](https://user-images.githubusercontent.com/6818236/90030204-c3184780-dc89-11ea-97e4-9656cd765351.png)

Please download the latest version off GitHub.

**Comment by Iv1ano** [comment]
Ah thanks CriticalFlaw! That's fixed it, but do update the version on huds.tf since that's where I got the fresh install. Thanks again!

**Comment by CriticalFlaw** [comment]
No problem. I've uploaded the correct version to huds.tf
