### ISSUE TITLE
White square when changing disguise on spy

### ISSUE THREAD

**Issue by omperus** [CriticalFlaw/rayshud-Installer#7]
![image](https://user-images.githubusercontent.com/4312673/42550550-cc6b394a-84a8-11e8-885d-89a6ca7e1b38.png)

![image](https://user-images.githubusercontent.com/4312673/42550572-ec5909e4-84a8-11e8-9061-62da504c34f2.png)

**Comment by CriticalFlaw** [comment]
Are you using the latest installer, version 1.2? Because of the changes to rayshud, the older versions of the installer break it. The new version will notify you of when a new version of the installer is out.

**Comment by CriticalFlaw** [comment]
Found and fixed the issue https://github.com/raysfire/rayshud/commit/6ebb87ca998e95cec9d2f8610144066c5a2d356d

Just refresh your rayshud installation and it should work
